[project]
name = "ghidramcp"
version = "1.4.0"
description = "A Model Context Protocol server for allowing LLMs to autonomously reverse engineer applications"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["mcp==1.5.0", "requests==2.32.3"]
